# Generated by Django 5.1.3 on 2024-11-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zipcode', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.product'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('orders', models.ManyToManyField(related_name='users', through='orm_app.OrderUser', to='orm_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='orderuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.user'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(related_name='addresses', through='orm_app.UserAddress', to='orm_app.user'),
        ),
    ]
